apiVersion: v1
kind: Pod
metadata:
  name: policy-test-hostpath
  namespace: test
  labels:
    app: test-hostpath
spec:
  containers:
  - name: hostpath-container
    image: busybox:latest
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp

