apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test3
spec:
  replicas: 2  # Desired state: 2 replicas
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80

