apiVersion: v1
kind: Pod
metadata:
  name: policy-test-privileged-pod
  namespace: test2
  labels:
    app: privileged-pod
spec:
  containers:
  - name: privileged-container
    image: nginx:latest
    securityContext:
      privileged: true

